# Generated by Django 3.1.4 on 2020-12-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
